# Generated by Django 3.1 on 2020-09-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armarios_system', '0003_auto_20200901_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='armario',
            name='colunas',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
