# Generated by Django 3.1 on 2020-09-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armarios_system', '0004_armario_colunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armario', models.IntegerField()),
                ('componentes', models.CharField(max_length=255)),
                ('barrageralhorizontal', models.IntegerField()),
                ('barrageralvertical', models.IntegerField()),
                ('barraneutro', models.IntegerField()),
                ('barraterra', models.IntegerField()),
                ('largura', models.IntegerField()),
                ('deleted_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
