# Generated by Django 3.1 on 2020-09-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armarios_system', '0006_auto_20200902_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='armario',
            name='linha',
            field=models.CharField(default='Linha', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='linha',
            field=models.CharField(default='Linha', max_length=255),
            preserve_default=False,
        ),
    ]
