# Generated by Django 3.1 on 2020-09-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armarios_system', '0007_auto_20200909_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armario',
            name='linha',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='linha',
        ),
    ]
