# Generated by Django 3.1 on 2020-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armarios_system', '0008_auto_20200909_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='armario',
            name='chapa',
            field=models.CharField(default='16#', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armario',
            name='formaconstrutiva',
            field=models.CharField(default='2A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armario',
            name='graudeprotecao',
            field=models.CharField(default='IP-3X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armario',
            name='icc',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armario',
            name='instalacao',
            field=models.CharField(default='Abrigado ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armario',
            name='linha',
            field=models.CharField(default='Linha', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armario',
            name='tensao',
            field=models.IntegerField(default=220),
            preserve_default=False,
        ),
    ]
