# Generated by Django 3.1 on 2020-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tensaoautomatic',
            name='value',
            field=models.IntegerField(),
        ),
    ]
