# Generated by Django 3.1 on 2020-08-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0002_auto_20200812_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TensaoAutomatic',
            new_name='Tensao',
        ),
    ]
