# Generated by Django 3.1 on 2020-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0004_componente_corrente_fabricantes_linhadeproducao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaConstrutiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('deleted_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GraudeProtecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('deleted_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ICC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('deleted_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Componente',
            new_name='Produto',
        ),
        migrations.DeleteModel(
            name='LinhadeProducao',
        ),
    ]
