# Generated by Django 3.1 on 2020-08-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0005_auto_20200823_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icc',
            name='value',
            field=models.FloatField(),
        ),
    ]
