# Generated by Django 3.1 on 2020-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0008_auto_20200823_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliername', models.CharField(max_length=255)),
                ('prodline', models.CharField(max_length=255)),
                ('corrente', models.IntegerField()),
                ('tensao', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('largura', models.IntegerField()),
                ('profundidade', models.IntegerField()),
                ('peso', models.FloatField()),
                ('icc127', models.FloatField()),
                ('icc220', models.FloatField()),
                ('icc380', models.FloatField()),
                ('icc440', models.FloatField()),
                ('icc480', models.FloatField()),
                ('deleted_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
